### ISSUE TITLE
"outline" mode (Eclipse ctrl-o)

### ISSUE THREAD

**Issue by justinmk** [ervandew/eclim#250]
Eclim is really impressive. Thanks.

Eclipse has an "Outline" dialog that shows a list of symbols in the current file (default Eclipse shortcut: `ctrl-o`). Is this feasible to implement in eclim? Or does it exist? I don't see a `:JavaFoo` command that supports it, and can't find an existing issue mentioning it.

I'd rather not have to use ctags for this.

**Comment by gopar** [comment]
Would this be somewhere in the right path to implementing the "outline" feature? 
https://gist.github.com/gopar/a593cc5b304df785e330

Feedback is appreciated :) Also where should this file be placed within the eclim project?

**Comment by kleewho** [comment]
@gopar You're faster coder then me ;)

**Comment by ervandew** [comment]
@gopar 
my biggest concern with your sample code is that I was hoping this command wouldn't be specific to any one language, because that would require having a command for each eclim language plugin. Instead, i'm wondering if the eclipse outline view has some language agnostic functions which eclim could utilize to just pull out the nodes, in which case one command can provide an outline result for any file eclipse supports outlines for.

**Comment by justinmk** [comment]
Well, event Eclipse doesn't have a generic "Quick Outline" concept. Instead, it uses the same name for different implementations which are initialized with the same mapping (usually; see the Dart Editor for a case where mappings diverge occasionally from Eclipse conventions). You can see this in the Keys preference dialog:

![image](https://cloud.githubusercontent.com/assets/1359421/8863179/5a3e1d00-3164-11e5-9883-0d4fee55a2eb.png)

If you export those keys preferences to an epf file, the JDT (or whatever) calls will be listed. This implies that there is no generic JDT "Quick Outline" function.

**Comment by gopar** [comment]
@ervandew From what I've seen outline mode in eclipse works with xml, groovy, JS and python files.

**Comment by justinmk** [comment]
> outline mode in eclipse works with xml, groovy, JS and python files

Yes, but each function call is different. Eclipse just happens to map Alt+O consistently for each "editor type".

**Comment by ervandew** [comment]
@justinmk 
just because the end points are different doesn't mean there isn't a common interface. I only spent a couple minutes looking, but it seems that the `IInformationControl*` interfaces might provide that. Whether or not they have enough to provide a generic eclim command is another matter though. If this can't be made totally generic, that's ok as long as there is a good reason for that.

**Comment by justinmk** [comment]
Ok, good to hear :)

**Comment by gopar** [comment]
So preferred approach is to try to use the `IInformationControl*` interfaces I assume?

**Comment by habitullence** [comment]
Was anything like this implemented in the end? Wouldn't it be possible to interface something like tagbar with Eclim?

**Comment by ervandew** [comment]
> Was anything like this implemented in the end?

This has not been implemented.

> Wouldn't it be possible to interface something like tagbar with Eclim?

tagbar doesn't need eclim to function, it just needs ctags, so you can use it with or without eclim.
