### ISSUE TITLE
eclim.org site is down.

### ISSUE THREAD

**Issue by fabianmurariu** [ervandew/eclim#411]
Hi eclim.org is taken over by sourceforge could you move it to github? Is it somwhere I'm not looking at?

**Comment by ervandew** [comment]
sourceforge is just currently having issues serving project web pages. They should hopefully be back soon.

**Comment by fabianmurariu** [comment]
You should consider moving

http://arstechnica.com/information-technology/2015/05/sourceforge-grabs-gimp-for-windows-account-wraps-installer-in-bundle-pushing-adware/

**Comment by ervandew** [comment]
I've seen the uproar, but that's not really related to where eclim hosts static html content.  It also use to be the case that using a custom domain with github required a paid account.  If that is no longer the case, then I might move the static content since sourceforge has had some reliability issues.

I've long wanted to move eclim's downloads over to github as well, but they've had a somewhat turbulant past with hosting of binaries. Hopefully their "Releases" are here to stay and doesn't go the way of their "Uploads". I'll think about moving that aspect of eclim over as well.

**Comment by jrosiek** [comment]
Please move just the static content (manual) somewhere else. It is terrible pain in the ... there is no manual available.

**Comment by ervandew** [comment]
@jrosiek 
You can access the docs in vim using `:EclimHelp`. The html docs also ship with eclim, so you can unzip `$ECLIPSE_HOME/plugins/org.eclim_<version>/doc.zip` and open `site/index.html` in your browser.

**Comment by ervandew** [comment]
@fabianmurariu 
@jrosiek 
Eclim docs and the new release are now available on github. Let me know if you notice any issues. I'll probably phase out sourceforge usage relatively soon.

Docs: http://ervandew.github.io/eclim/
Release: https://github.com/ervandew/eclim/releases/tag/2.5.0
