### ISSUE TITLE
Rails completion fails because of the short lambda syntax

### ISSUE THREAD

**Issue by eugen0329** [ervandew/eclim#439]
Rails model completion corrupts due to 'syntax error, unexpected tGT', appearing when I'm trying to define ActiveRecord scope with short lambda syntax (->{}):

class AnyModel < ActiveRecord::Base
  scope :unnamed, -> { where(name: nil) }
end

Steps to reproduce:
1) $ rails new eclim_test_project
2) $ cd ./eclim_test_project
3) rails g scaffold any_model
4) vim app/models/any_model.rb
5) Insert 'scope :unnamed, -> { where(name: nil) }' line into the model
6) ':ProjectProblems' results:
   1 app/models/any_model.rb|3 col 20 error| syntax error, unexpected tGT 

There is a bug request on https://bugs.eclipse.org/bugs/show_bug.cgi?format=multiple&id=448604
and similar post on https://www.ruby-forum.com/topic/199845#870752.

According to the last link reply:
> irb(main):001:0> ->{}
> SyntaxError: (irb):2: , unexpected tGT
> ->{}
This seems to be fixed post JRuby-1.4. So, it works on master branch
(and will work in official 1.5 release).

Probably, the issue lies in old jruby version?

**Comment by ervandew** [comment]
There's nothing really that eclim can do here since it simply relies on eclipse for these results.

I would hope that they would fix this upstream, but the fact that the bug you posted is a year old, isn't very promising.  For now you can tell eclim to ignore this error using something like this in a ruby ftplugin:

    let b:EclimLocationListFilter = ['syntax error, unexpected tGT']

Unfortunately though, other legitimate syntax errors with that same message will be ignored as well :/
